#! /bin/sh

if [ $# -ne 1 ] ; then
   echo "error $0 needs a single parameter :"
   echo "s : start/stop the trheadmill"
   echo "p : increase speed"
   echo "m : decrease speed"
fi

echo -n $1 | socat - UDP:127.0.0.1:5005
